from __future__ import annotations

import json
from pathlib import Path

from backend.app_factory.schemas import ArchitectureSpec, GeneratedFile, RequirementsSpec


ROOT = Path.cwd()
GENERATED_ROOT = ROOT / "generated_apps"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def _page(requirements: RequirementsSpec) -> str:
    features = json.dumps(requirements.core_features[:4])
    return '''
"use client";

import {{ useEffect, useMemo, useState }} from "react";
import {{ loadItems, saveItems, type AppItem }} from "../lib/storage";

const features = %%FEATURES%%;

export default function Page() {{
  const [items, setItems] = useState<AppItem[]>([]);
  const [title, setTitle] = useState("");
  const [details, setDetails] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {{
    setItems(loadItems());
  }}, []);

  useEffect(() => {{
    saveItems(items);
  }}, [items]);

  const completed = useMemo(
    () => items.filter((item) => item.status === "done").length,
    [items],
  );

  function addItem() {{
    if (!title.trim()) {{
      setError("Add a short title first.");
      return;
    }}
    setItems((current) => [
      {{
        id: crypto.randomUUID(),
        title: title.trim(),
        details: details.trim(),
        status: "active",
        createdAt: new Date().toISOString(),
      }},
      ...current,
    ]);
    setTitle("");
    setDetails("");
    setError("");
  }}

  function toggleItem(id: string) {{
    setItems((current) =>
      current.map((item) =>
        item.id === id
          ? {{ ...item, status: item.status === "done" ? "active" : "done" }}
          : item,
      ),
    );
  }}

  function removeItem(id: string) {{
    setItems((current) => current.filter((item) => item.id !== id));
  }}

  return (
    <main className="min-h-screen bg-neutral-950 px-5 py-8 text-neutral-100">
      <div className="mx-auto max-w-5xl">
        <header className="mb-8">
          <p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-300">
            Generated by RepoMentor AI App Factory
          </p>
          <h1 className="mt-3 text-4xl font-semibold tracking-tight">
            %%APP_NAME%%
          </h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-400">
            A focused single-user demo app for %%TARGET_USER%%
          </p>
        </header>

        <section className="grid gap-4 md:grid-cols-3">
          <div className="rounded-lg border border-neutral-800 bg-neutral-900 p-4">
            <p className="text-xs uppercase tracking-[0.18em] text-neutral-500">Items</p>
            <p className="mt-2 text-3xl font-semibold">{{items.length}}</p>
          </div>
          <div className="rounded-lg border border-neutral-800 bg-neutral-900 p-4">
            <p className="text-xs uppercase tracking-[0.18em] text-neutral-500">Done</p>
            <p className="mt-2 text-3xl font-semibold">{{completed}}</p>
          </div>
          <div className="rounded-lg border border-neutral-800 bg-neutral-900 p-4">
            <p className="text-xs uppercase tracking-[0.18em] text-neutral-500">Mode</p>
            <p className="mt-2 text-lg font-medium">Local browser demo</p>
          </div>
        </section>

        <section className="mt-6 rounded-lg border border-neutral-800 bg-neutral-900 p-5">
          <h2 className="text-lg font-medium">Add an item</h2>
          <div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]">
            <input
              className="rounded-md border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
              onChange={(event) => setTitle(event.target.value)}
              placeholder="Title"
              value={{title}}
            />
            <input
              className="rounded-md border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
              onChange={(event) => setDetails(event.target.value)}
              placeholder="Details"
              value={{details}}
            />
            <button
              className="rounded-md bg-emerald-300 px-4 py-2 text-sm font-semibold text-neutral-950"
              onClick={{addItem}}
              type="button"
            >
              Add
            </button>
          </div>
          {{error ? <p className="mt-3 text-sm text-red-300">{{error}}</p> : null}}
        </section>

        <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]">
          <div className="rounded-lg border border-neutral-800 bg-neutral-900 p-5">
            <h2 className="text-lg font-medium">Workspace</h2>
            <div className="mt-4 space-y-3">
              {{items.length === 0 ? (
                <div className="rounded-md border border-dashed border-neutral-700 p-6 text-sm text-neutral-400">
                  No items yet. Add one above to start the workflow.
                </div>
              ) : (
                items.map((item) => (
                  <article
                    className="rounded-md border border-neutral-800 bg-neutral-950 p-4"
                    key={{item.id}}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <h3 className="font-medium">{{item.title}}</h3>
                        {{item.details ? (
                          <p className="mt-1 text-sm text-neutral-400">{{item.details}}</p>
                        ) : null}}
                      </div>
                      <span className="rounded-full border border-neutral-700 px-2 py-1 text-xs text-neutral-400">
                        {{item.status}}
                      </span>
                    </div>
                    <div className="mt-4 flex gap-2">
                      <button
                        className="rounded-md border border-neutral-700 px-3 py-1.5 text-xs"
                        onClick={{() => toggleItem(item.id)}}
                        type="button"
                      >
                        Toggle status
                      </button>
                      <button
                        className="rounded-md border border-red-900/70 px-3 py-1.5 text-xs text-red-300"
                        onClick={{() => removeItem(item.id)}}
                        type="button"
                      >
                        Remove
                      </button>
                    </div>
                  </article>
                ))
              )}}
            </div>
          </div>

          <aside className="rounded-lg border border-neutral-800 bg-neutral-900 p-5">
            <h2 className="text-lg font-medium">Core features</h2>
            <ul className="mt-4 space-y-3 text-sm text-neutral-400">
              {{features.map((feature) => (
                <li className="rounded-md bg-neutral-950 p-3" key={{feature}}>
                  {{feature}}
                </li>
              ))}}
            </ul>
          </aside>
        </section>
      </div>
    </main>
  );
}}
'''.replace("%%FEATURES%%", features).replace(
        "%%APP_NAME%%",
        requirements.app_name,
    ).replace("%%TARGET_USER%%", requirements.target_user).replace("{{", "{").replace("}}", "}")


def generate_app_files(
    requirements: RequirementsSpec,
    architecture: ArchitectureSpec,
) -> tuple[Path, list[GeneratedFile]]:
    app_path = GENERATED_ROOT / requirements.app_slug
    app_path.mkdir(parents=True, exist_ok=True)

    files: dict[str, str] = {
        "app/page.tsx": _page(requirements),
        "app/layout.tsx": f'''
import "./globals.css";
import type {{ Metadata }} from "next";
import type {{ ReactNode }} from "react";

export const metadata: Metadata = {{
  title: "{requirements.app_name}",
  description: "Generated by RepoMentor AI App Factory",
}};

export default function RootLayout({{ children }}: {{ children: ReactNode }}) {{
  return (
    <html lang="en">
      <body>{{children}}</body>
    </html>
  );
}}
''',
        "app/globals.css": '''
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: #0a0a0a;
}
''',
        "lib/storage.ts": '''
export type AppItem = {
  id: string;
  title: string;
  details: string;
  status: "active" | "done";
  createdAt: string;
};

const STORAGE_KEY = "app-factory-items";

export function loadItems(): AppItem[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as AppItem[]) : [];
  } catch {
    return [];
  }
}

export function saveItems(items: AppItem[]) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
  } catch {
    // Demo apps should stay usable even when localStorage is unavailable.
  }
}
''',
        "tests/smoke.test.mjs": '''
import { existsSync } from "node:fs";

const required = [
  "app/page.tsx",
  "app/layout.tsx",
  "app/globals.css",
  "package.json",
  "Dockerfile",
  "README.md",
];

for (const file of required) {
  if (!existsSync(file)) {
    throw new Error(`Missing required file: ${file}`);
  }
}

console.log("Smoke test passed.");
''',
        "package.json": json.dumps(
            {
                "name": requirements.app_slug,
                "version": "0.1.0",
                "private": True,
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "sh -c 'next start -H 0.0.0.0 -p ${PORT:-8080}'",
                    "test": "node tests/smoke.test.mjs",
                },
                "dependencies": {
                    "next": "16.2.0",
                    "react": "19.0.1",
                    "react-dom": "19.0.1",
                },
                "devDependencies": {
                    "@types/node": "^22.8.6",
                    "@types/react": "^18",
                    "@types/react-dom": "^18",
                    "typescript": "^5.6.3",
                },
            },
            indent=2,
        ),
        "tsconfig.json": json.dumps(
            {
                "compilerOptions": {
                    "target": "ES2017",
                    "lib": ["dom", "dom.iterable", "esnext"],
                    "allowJs": True,
                    "skipLibCheck": True,
                    "strict": True,
                    "noEmit": True,
                    "esModuleInterop": True,
                    "module": "esnext",
                    "moduleResolution": "bundler",
                    "resolveJsonModule": True,
                    "isolatedModules": True,
                    "jsx": "preserve",
                    "incremental": True,
                    "plugins": [{"name": "next"}],
                    "paths": {"@/*": ["./*"]},
                },
                "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                "exclude": ["node_modules"],
            },
            indent=2,
        ),
        "next.config.js": "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;\n",
        "Dockerfile": '''
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app ./
EXPOSE 8080
CMD ["npm", "start"]
''',
        ".dockerignore": "node_modules\n.next\n.env\n.env.local\n*.log\n",
    }

    for path, content in files.items():
        _write(app_path / path, content)

    generated = [
        GeneratedFile(path=path, description="Generated Next.js app file")
        for path in sorted(files)
    ]
    return app_path, generated
