from __future__ import annotations

from pathlib import Path

from backend.app_factory.schemas import AgentRunResult, ArchitectureSpec, RequirementsSpec


def write_docs(app_path: Path, requirements: RequirementsSpec, architecture: ArchitectureSpec) -> AgentRunResult:
    docs = {
        "README.md": f"""# {requirements.app_name}

Generated by RepoMentor AI App Factory.

## What It Does

{requirements.target_user}

## Core Features

{chr(10).join(f"- {feature}" for feature in requirements.core_features)}

## Run Locally

```bash
npm install
npm run dev
```

## Production

```bash
npm run build
npm start
```
""",
        "architecture.md": f"""# Architecture

## Framework

- Framework: {architecture.framework}
- Language: {architecture.language}
- Router: {architecture.router}

## Components

{chr(10).join(f"- {item}" for item in architecture.components)}

## Data Flow

{chr(10).join(f"- {item}" for item in architecture.data_flow)}
""",
        "usage.md": f"""# Usage

## Primary User Flow

{chr(10).join(f"- {step}" for step in requirements.user_flow)}

## Acceptance Criteria

{chr(10).join(f"- {item}" for item in requirements.acceptance_criteria)}
""",
        "limitations.md": f"""# Limitations

{chr(10).join(f"- {item}" for item in architecture.limitations)}

This generated app is intended as a safe single-user demo. It does not include auth,
payments, sensitive-data handling, or production backend integrations.
""",
        "deployment.md": """# Cloud Run Deployment

Set these environment variables before deployment:

```bash
export GCP_PROJECT_ID="your-project-id"
export GCP_REGION="us-central1"
export GCP_ARTIFACT_REPOSITORY="cloud-run-source-deploy"
```

Build and deploy:

```bash
gcloud builds submit --tag "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REPOSITORY/$APP_SLUG"
gcloud run deploy "$APP_SLUG" \\
  --image "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REPOSITORY/$APP_SLUG" \\
  --platform managed \\
  --region "$GCP_REGION" \\
  --allow-unauthenticated
```
""",
    }

    for name, content in docs.items():
        (app_path / name).write_text(content.strip() + "\n", encoding="utf-8")

    return AgentRunResult(
        status="passed",
        summary="README, architecture, usage, limitations, and deployment docs generated.",
    )

